//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gorodnitsevAutocompliterProj2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NameInfo
    {
        public int Id { get; set; }
        public string Emakeelnenimi { get; set; }
        public string Sugu { get; set; }
        public string Voorkeelnenimi { get; set; }
        public int AdminSet { get; set; }
    }
}
